# Generated by Django 5.0.4 on 2024-04-21 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_post_comments_comment_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('place_image', models.ImageField(blank=True, null=True, upload_to='places/')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='api.university')),
            ],
        ),
    ]
