# Generated by Django 5.0.4 on 2024-04-21 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_skill_user_description_alter_post_author_user_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='university',
        ),
    ]
